from collections import OrderedDict



periods = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18']
tableElements =[['H ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', 'He'], 
                ['Li', 'Be', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', 'B ', 'C ', 'N ', 'O ', 'F ', 'Ne'], 
                ['Na', 'Mg', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', 'Al', 'Si', 'P ', 'S ', 'Cl', 'Ar'],
                ['K ', 'Ca', 'Sc', 'Ti', 'V ', 'Cr', 'Mn', 'Fe', 'Co', 'Ni', 'Cu', 'Zn', 'Ga', 'Ge', 'As', 'Se', 'Br', 'Kr'],
                ['Rb', 'Sr', 'Y ', 'Zr', 'Nb', 'Mo', 'Tc', 'Ru', 'Rh', 'Pd', 'Ag', 'Cd', 'In', 'Sn', 'Sb', 'Te', 'I ', 'Xe'], 
                ['Cs', 'Ba', '↓ ', 'Hf', 'Ta', 'W ', 'Re', 'Os', 'Ir', 'Pt', 'Au', 'Hg', 'Tl', 'Pb', 'Bi', 'Po', 'At', 'Rn'], 
                ['Fr', 'Ra', '↓ ', 'Rf', 'Db', 'Sg', 'Bh', 'Hs', 'Mt', 'Ds', 'Rg', 'Cn', 'Nh', 'Fl', 'Mc', 'Lv', 'Ts', 'Og'],
                ['  ', '  ', '↓ ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  '],
                ['  ', '  ', '→|', 'La', 'Ce', 'Pr', 'Nd', 'Pm', 'Sm', 'Eu', 'Gd', 'Tb', 'Dy', 'Ho', 'Er', 'Tm', 'Yb', 'Lu'],
                ['  ', '  ', '→|', 'Ac', 'Th', 'Pa', 'U ', 'Np', 'Pu', 'Am', 'Cm', 'Bk', 'Cf', 'Es', 'Fm', 'Md', 'No', 'Lr']
                ]



chemInfo= ['',
          '*To escape this widget, click another*',
          'Press L to search, and n to cycle results. Case sensitive',
          '',
          ' -- TABLE OF CONTENTS --',
          'Table Trends',
          'Element Info',
          'Conversions and Constants',
          'Other Info',
          ' ',
          '-- Table Trends --',
          ' ',
          '→Left to Right→',
          '    Atomic Radius Decreases',
          '    Ionization Energy Increases',
          '    Electronegativity Increases',
          '    Electron Affinity Increases',
          ' ',
          '↓Top to Bottom↓',
          '    Atomic Radius Increases',
          '    Ionization Energy Decreases',
          '    Electronegativity Decreases',
          '    Electron  Affinity Decreases',
          ' ',
          '-- Element Info --',
          ' ',
          'Diatomic Elements: H₂, N₂, O₂, F₂, Cl₂, Br₂, I₂',
          '',
          '-- Conversions and Constants --',
          ' ',
          'Kelvin = ˚C + 273.15',
          'Ceslsius = (˚F -32) × (5/9)',
          'Speed of Light = 3x10⁸ or 300,000,000 m/s',
          'Plankc\'s Constant = 6.62607004 × 10⁻³⁴ J⋅s',
          'Avagadros Number = 6.0221409 × 10²³',
          ' ',
          '-- Other Info --',
          ' ',
          'Solid → Liquid: Melting',
          'Solid → Gas: Sublimation',
          'Liquid → Gas: Vaporization',
          'Liquid → Solid: Fusion',
          'Gas → Liquid: Condensation',
          'Gas → Solid: Deposition']




elementStats = {'H': OrderedDict([('Name:', 'Hydrogen'),
        ('Atomic Number:', 1),
        ('Group:', 1),
        ('Period:', 1),
        ('Block:', 's'),
        ('Category', 'Reactive Nonmetal'),
        ('Atomic Mass (u):', 1.00794),
        ('Electronegativity:', 2.20),
        ('Electron Configuration:', '1s¹'),
        ('Phase at STP:', 'Gas'), 
        ('Melting Point (K):', 13.99),
        ('Boiling Point (K):', 20.271),
        ('Density at STP (g/L):', 0.08988),
        ('Triple Point (K):', 13.8033),
        ('Critical Point (K):', 32.938),
        ('Heat Capacity (J/(mol·K)):', 28.836),
        ('Oxidation States:', '-1, +1'),
        ('Covalent Radius (pm):', '31±5'),
        ('Van Der Waals Radius (pm):', 120),
        ('Crystal Structure:', 'Hexagonal'),
        ('Speed of Sound (gas, 27˚C, m/s)', 1310),
        ('Thermal Conductivity (W/(m·K))', 0.1805),
        ('Magnetic Ordering:', 'Diamagnetic')]),
    
    'He': OrderedDict([('Name:', 'Helium'),
        ('Atomic Number:', 2),
        ('Group:', 18),
        ('Period:', 1),
        ('Block:', 's'),
        ('Category', 'Noble Gas'),
        ('Atomic Mass (u):', 4.002602),
        ('Electronegativity:', 'No Data'),
        ('Electron Configuration:', '1s²'),
        ('Phase at STP:', 'Gas'),
        ('Melting Point (K):', 0.95),
        ('Boiling Point (K):', 4.222),
        ('Density at STP (g/L):', 0.1786),
        (' → at Melting Point (g/cm³):', 0.145),
        ('Triple Point (K):', 2.117),
        ('Critical Point (K):', 5.1953),
        ('Heat Capacity (J/(mol·K)):', 20.78),
        ('Oxidation States:', '0'),
        ('Covalent Radius (pm):', '28'),
        ('Van Der Waals Radius (pm):', 140),
        ('Crystal Structure:', 'Hexagonal Close-Packed'),
        ('Thermal Conductivity (W/(m·K))', 0.1513),
        ('Magnetic Ordering:', 'Diamagnetic')]),


    'Li': OrderedDict([('Name:', 'Lithium'),
        ('Atomic Number:', 3),
        ('Group:', 1),
        ('Period:', 2),
        ('Block:', 's'),
        ('Category', 'Alkali Metal'),
        ('Atomic Mass (u):', 6.94),
        ('Electronegativity:', 0.98),
        ('Electron Configuration:', '[He]2s¹'),
        ('Phase at STP:', 'Solid'),
        ('Melting Point (K):', 453.65),
        ('Boiling Point (K):', 1603),
        ('Density at RT (g/cm³):', 0.534),
        (' → at Melting Point (g/cm³):', 0.512),
        ('Critical Point (K):', 3220),
        ('Heat of Fusion (kJ/mol):', 3.00 ),
        ('Heat of Vaporization (kJ/mol):', 136),
        ('Heat Capacity (J/(mol·K)):', 24.860),
        ('Oxidation States:', '+1'),
        ('Atomic Radius (pm):', 152),
        ('Covalent Radius (pm):', '128±7'),
        ('Van Der Waals Radius (pm):', 182),
        ('Crystal Structure:', 'Body-Centric Cubic'),
        ('Thermal Expansion at 25˚C: (µm/(m·K))', 46),
        ('Thermal Conductivity (W/(m·K))', 84.8),
        ('Electrical Resistivity at 25˚C (nΩ·m)', 98.2),
        ('Magnetic Ordering:', 'Paramagnetic')]),
        
            
    'Be': OrderedDict([('Name:', 'Beryllium'),
        ('Atomic Number:', 4),
        ('Group:', 2),
        ('Period:', 2),
        ('Block:', 's'),
        ('Category', 'Alkaline Earth Metal'),
        ('Atomic Mass (u):', 9.012),
        ('Electronegativity:', 1.57),
        ('Electron Configuration:', '[He]2s²'),
        ('Phase at STP:', 'Solid'),
        ('Melting Point (K):', 1560),
        ('Boiling Point (K):', 2742),
        ('Density at RT (g/cm³):', 1.85),
        (' → at Melting Point (g/cm³):', 1.690),
        ('Critical Point (K):', 5205),
        ('Heat of Fusion (kJ/mol):', 12.2 ),
        ('Heat of Vaporization (kJ/mol):', 292),
        ('Heat Capacity (J/(mol·K)):', 16.443),
        ('Oxidation States:', '+2, +1'),
        ('Atomic Radius (pm):', 112),
        ('Covalent Radius (pm):', '96±3'),
        ('Van Der Waals Radius (pm):', 153),
        ('Crystal Structure:', 'Hexagonal Closed-Packed'),
        ('Thermal Expansion at 25˚C: (µm/(m·K))', 11.3),
        ('Thermal Conductivity (W/(m·K))', 200),
        ('Electrical Resistivity at 25˚C (nΩ·m)', 36),
        ('Magnetic Ordering:', 'Diamagnetic')]),

    'B': OrderedDict([('Name:', 'Boron'),
        ('Atomic Number:', 5),
        ('Group:', 13),
        ('Period:', 2),
        ('Block:', 'p'),
        ('Category', 'Metalloid'),
        ('Atomic Mass (u):', 10.81),
        ('Electronegativity:', 2.04),
        ('Electron Configuration:', '[He]2s²2p¹'),
        ('Phase at STP:', 'Solid'),
        ('Melting Point (K):', 2349),
        ('Boiling Point (K):', 4200),
        ('Density at Melting Point (g/cm³):', 2.08),
        ('Heat of Fusion (kJ/mol):', 50.2 ),
        ('Heat of Vaporization (kJ/mol):', 508),
        ('Heat Capacity (J/(mol·K)):', 11.087),
        ('Oxidation States:', '+3, +2, +1, -1, -5'),
        ('Atomic Radius (pm):', 90),
        ('Covalent Radius (pm):', '84±3'),
        ('Van Der Waals Radius (pm):', 192),
        ('Crystal Structure:', 'Rhombohedral'),
        ('Thermal Expansion at 25˚C: (µm/(m·K))', 6),
        ('Thermal Conductivity (W/(m·K))', 27.4),
        ('Electrical Resistivity at 20˚C (Ω·m)', '10⁶'),
        ('Magnetic Ordering:', 'Diamagnetic')]),
            
        
    'C': OrderedDict([('Name:', 'Carbon'),
        ('Atomic Number:', 6),
        ('Group:', 14),
        ('Period:', 2),
        ('Block:', 'p'),
        ('Category', 'Reactive Nonmetal/Metalloid'),
        ('Atomic Mass (u):', 12.011),
        ('Electron Configuration:', '[He]2s²2p²'),
        ('Phase at STP:', 'Solid'),
        ('Sublimation Point (K):', 3915),
        ('Triple Point (K):', 4600),
        ('Density at RT (g/cm³):', '1.8-2.1'),
        ('Heat of Fusion (kJ/mol):', 117),
        ('Heat of Vaporization (kJ/mol):', 508),
        ('Heat Capacity (J/(mol·K)):', '8.517 Graphite, 6.155 Diamond'),
        ('Oxidation States:', '+4, +3, +2, +1, 0, -1, -2, -3, -4'),
        ('Atomic Radius (pm):', 70),
        ('Covalent Radius (pm):', '69-77'),
        ('Van Der Waals Radius (pm):', 170),
        ('Crystal Structure:', 'Simple Hexagonal'),
        ('Thermal Expansion at 25˚C: (µm/(m·K))', 0.8),
        ('Thermal Conductivity (W/(m·K))', '119-165 Graphite, 900-2300 Diamond'),
        ('Electronegativity:', 2.55),
        ('Electrical Resistivity at 20˚C (µΩ·m)', 7.837),
        ('Magnetic Ordering:', 'Diamagnetic')]),
    

    'N': OrderedDict([('Name:', 'Nitrogen'),
        ('Atomic Number:', 7),
        ('Group:', 15),
        ('Period:', 2),
        ('Block:', 'p'),
        ('Category', 'Reactive Nonmetal'),
        ('Atomic Mass (u):', 14.007),
        ('Electron Configuration:', '[He]2s²2p³'),
        ('Phase at STP:', 'Gas'),
        ('Melting Point (K):', 63.15),
        ('Boiling Point (K):', 77.377),
        ('Triple Point (K):', '63.151 at 12.52 kPa'),
        ('Critical Point (K):', '126.192 at 3.3958 MPa'),
        ('Density at STP (g/L):', '1.2504 at 0˚C, 1013 mbar'),
        ('Heat of Fusion (kJ/mol):', 0.72),
        ('Heat of Vaporization (kJ/mol):', 5.56),
        ('Heat Capacity (J/(mol·K)):', 29.124),
        ('Oxidation States:', '+5, +4, +3, +2, +1, -1, -2, -3'),
        ('Covalent Radius (pm):', '71±1'),
        ('Van Der Waals Radius (pm):', 155),
        ('Crystal Structure:', 'Hexagonal'),
        ('Thermal Conductivity (W/(m·K))', '25.83x10⁻³'),
        ('Electronegativity:', 3.04),
        ('Magnetic Ordering:', 'Diamagnetic')]),
    
    'O': OrderedDict([('Name:', 'Oxygen'),
        ('Atomic Number:', 8),
        ('Group:', 16),
        ('Period:', 2),
        ('Block:', 'p'),
        ('Category', 'Reactive Nonmetal'),
        ('Atomic Mass (u):', 15.999),
        ('Electron Configuration:', '[He]2s²2p⁴'),
        ('Phase at STP:', 'Gas'),
        ('Melting Point (K):', 54.36),
        ('Boiling Point (K):', 90.188),
        ('Triple Point (K):', '54.361 at 0.1463 kPa'),
        ('Critical Point (K):', '154.581 at 5.043 MPa'),
        ('Density at STP (g/L):', 1.429),
        ('Heat of Fusion (kJ/mol):', 0.444),
        ('Heat of Vaporization (kJ/mol):', 6.82),
        ('Heat Capacity (J/(mol·K)):', 29.378),
        ('Oxidation States:', '+2, +1, -1, -2'),
        ('Covalent Radius (pm):', '66±2'),
        ('Van Der Waals Radius (pm):', 152),
        ('Crystal Structure:', 'Cubic'),
        ('Thermal Conductivity (W/(m·K))', '26.53x10⁻³'),
        ('Electronegativity:', 3.44),
        ('Magnetic Ordering:', 'Paramagnetic')])

        }
