from collections import OrderedDict



periods = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18']

tableElements =[['H ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', 'He'], 
                ['Li', 'Be', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', 'B ', 'C ', 'N ', 'O ', 'F ', 'Ne'], 
                ['Na', 'Mg', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', 'Al', 'Si', 'P ', 'S ', 'Cl', 'Ar'],
                ['K ', 'Ca', 'Sc', 'Ti', 'V ', 'Cr', 'Mn', 'Fe', 'Co', 'Ni', 'Cu', 'Zn', 'Ga', 'Ge', 'As', 'Se', 'Br', 'Kr'],
                ['Rb', 'Sr', 'Y ', 'Zr', 'Nb', 'Mo', 'Tc', 'Ru', 'Rh', 'Pd', 'Ag', 'Cd', 'In', 'Sn', 'Sb', 'Te', 'I ', 'Xe'], 
                ['Cs', 'Ba', ' ↓', 'Hf', 'Ta', 'W ', 'Re', 'Os', 'Ir', 'Pt', 'Au', 'Hg', 'Tl', 'Pb', 'Bi', 'Po', 'At', 'Rn'], 
                ['Fr', 'Ra', ' ↓', 'Rf', 'Db', 'Sg', 'Bh', 'Hs', 'Mt', 'Ds', 'Rg', 'Cn', 'Nh', 'Fl', 'Mc', 'Lv', 'Ts', 'Og'],
                ['  ', '  ', ' ↓', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ', '  '],
                ['  ', '  ', '→|', 'La', 'Ce', 'Pr', 'Nd', 'Pm', 'Sm', 'Eu', 'Gd', 'Tb', 'Dy', 'Ho', 'Er', 'Tm', 'Yb', 'Lu'],
                ['  ', '  ', '→|', 'Ac', 'Th', 'Pa', 'U ', 'Np', 'Pu', 'Am', 'Cm', 'Bk', 'Cf', 'Es', 'Fm', 'Md', 'No', 'Lr']
                ]



chemInfo= ['',
          '########################',
          '## Table of Contents ###',
          '########################',
          ' ',
          'Table Info',
          'Element Facts',
          'Conversions and Constants',
          'Other Info',
          ' ',
          '-- Table Info --',
          ' ',
          '- Trends -',
          '→Left to Right→',
          '    Atomic Radius Decreases',
          '    Ionization Energy Increases',
          '    Electronegativity Increases',
          '    Electron Affinity Increases',
          ' ',
          '↓Top to Bottom↓',
          '    Atomic Radius Increases',
          '    Ionization Energy Decreases',
          '    Electronegativity Decreases',
          '    Electron  Affinity Decreases',
          ' ',
          ' - Groups - ',
          'Group 1: Alkali Metals',
          'Group 2: Alkaline Earth Metals',
          'Group 11: Coinage Metals (not an IUPAC approved name)',
          'Group 15: Pnictogens (not an IUPAC approved name)',
          'Group 16: Chalcogens',
          'Group 17: Halogens',
          'Group 18: Noble Gases',
          ' ',
          ' ',
          '-- Element Info --',
          ' ',
          'Diatomic Elements: H₂, N₂, O₂, F₂, Cl₂, Br₂, I₂',
          '',
          '-- Conversions and Constants --',
          ' ',
          'Kelvin = ˚C + 273.15',
          'Celsius = (˚F -32) × (5/9)',
          'Speed of Light = 3x10⁸ or 300,000,000 m/s',
          'Plankc\'s Constant = 6.62607004 × 10⁻³⁴ J⋅s',
          'Avagadros Number = 6.0221409 × 10²³',
          ' ',
          '-- Other Info --',
          ' ',
          'Solid → Liquid: Melting',
          'Solid → Gas: Sublimation',
          'Liquid → Gas: Vaporization',
          'Liquid → Solid: Fusion',
          'Gas → Liquid: Condensation',
          'Gas → Solid: Deposition']
